version: '3.9'
services:
  api:
    container_name: "backend"
    build: ./api
    restart: unless-stopped
    ports:
      - 5000:5000
      - 5909:5909
  ui:
    container_name: "frontend"
    build: ./ui
    restart: unless-stopped
    ports:
      - 3000:3000

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data