version: '3.9'
services:
  express-server:
    container_name: "express"
    build: ./express
    restart: unless-stopped
    ports:
      - 5000:5000
  ui:
    container_name: "ui-react"
    build: ./ui
    restart: unless-stopped
    ports:
      - 3000:3000
